CREATE TABLE lo54.LOCATION (
	PK_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	CITY VARCHAR(20) NOT NULL,
	PRIMARY KEY (PK_ID)
);

CREATE TABLE lo54.COURSE (
	PK_CODE INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	PRIMARY KEY (PK_CODE)
);

CREATE TABLE lo54.COURSE_SESSION(
	PK_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	START_DATE DATE,
	END_DATE DATE,
        FK_COURSE_CODE INTEGER,
        FK_LOCATION_ID INTEGER,
	PRIMARY KEY (PK_ID)
        
);


CREATE TABLE lo54.CLIENT(
	PK_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	LASTNAME VARCHAR(20) NOT NULL,
	FIRSTNAME VARCHAR(20) NOT NULL,
	ADDRESS VARCHAR (50) NOT NULL,
	PHONE VARCHAR (16) NOT NULL,
	EMAIL VARCHAR(25) NOT NULL,
        FK_COURSE_SESSION INTEGER,
	PRIMARY KEY (PK_ID)
);




ALTER TABLE lo54.COURSE_SESSION
	ADD FOREIGN KEY (FK_COURSE_CODE) 
	REFERENCES lo54.COURSE (PK_CODE);

ALTER TABLE lo54.COURSE_SESSION
	ADD FOREIGN KEY (FK_LOCATION_ID) 
	REFERENCES lo54.LOCATION (PK_ID);

ALTER TABLE lo54.CLIENT
	ADD FOREIGN KEY (FK_COURSE_SESSION)
	REFERENCES lo54.COURSE_SESSION (PK_ID);



INSERT INTO lo54.CLIENT (LASTNAME, FIRSTNAME, ADDRESS, PHONE, EMAIL) 
	VALUES ('De Funes', 'Louis','Saint Tropez','03 84 56 84 78','blabla@blabla.bla');
INSERT INTO lo54.CLIENT (LASTNAME, FIRSTNAME, ADDRESS, PHONE, EMAIL) 
	VALUES ('Reno', 'Jean','Paris','03 84 56 84 79','blabla@blabla.bla');
INSERT INTO lo54.CLIENT (LASTNAME, FIRSTNAME, ADDRESS, PHONE, EMAIL) 
	VALUES ('Garcia', 'José','Marseille','03 84 56 84 80','blabla@blabla.bla');
INSERT INTO lo54.CLIENT (LASTNAME, FIRSTNAME, ADDRESS, PHONE, EMAIL) 
	VALUES ('Gere', 'Richard','Lyon','03 84 56 84 81','blabla@blabla.bla');
INSERT INTO lo54.CLIENT (LASTNAME, FIRSTNAME, ADDRESS, PHONE, EMAIL) 
	VALUES ('Stalone', 'Sylvester','Strasbourg','03 84 56 84 82','blabla@blabla.bla');
INSERT INTO lo54.CLIENT (LASTNAME, FIRSTNAME, ADDRESS, PHONE, EMAIL) 
	VALUES ('Bullock', 'Sandra','Rennes','03 84 56 84 83','blabla@blabla.bla');
INSERT INTO lo54.CLIENT (LASTNAME, FIRSTNAME, ADDRESS, PHONE, EMAIL) 
	VALUES ('Waver', 'Sigourney','Nantes','03 84 56 84 84','blabla@blabla.bla');
INSERT INTO lo54.CLIENT (LASTNAME, FIRSTNAME, ADDRESS, PHONE, EMAIL) 
	VALUES ('Di Caprio', 'Leonardo','Bordeaux','03 84 56 84 85','blabla@blabla.bla');
INSERT INTO lo54.CLIENT (LASTNAME, FIRSTNAME, ADDRESS, PHONE, EMAIL) 
	VALUES ('Winslett', 'Kate','Toulouse','03 84 56 84 86','blabla@blabla.bla');
INSERT INTO lo54.CLIENT (LASTNAME, FIRSTNAME, ADDRESS, PHONE, EMAIL) 
	VALUES ('Barymore', 'Drew','Los Angeles','03 84 56 84 87','blabla@blabla.bla');
INSERT INTO lo54.CLIENT (LASTNAME, FIRSTNAME, ADDRESS, PHONE, EMAIL) 
	VALUES ('Statham', 'Jason','London','03 84 56 84 88','blabla@blabla.bla');
INSERT INTO lo54.CLIENT (LASTNAME, FIRSTNAME, ADDRESS, PHONE, EMAIL) 
	VALUES ('Schwarzenegger', 'Arnold','San-Fransisco','03 84 56 84 89','blabla@blabla.bla');
INSERT INTO lo54.CLIENT (LASTNAME, FIRSTNAME, ADDRESS, PHONE, EMAIL) 
	VALUES ('Roberts', 'Julia','New-York','03 84 56 84 90','blabla@blabla.bla');


INSERT INTO lo54.LOCATION(CITY) 
	VALUES ('BELFORT');
INSERT INTO lo54.LOCATION(CITY) 
	VALUES ('MULHOUSE');
INSERT INTO lo54.LOCATION(CITY) 
	VALUES ('BESANCON');
INSERT INTO lo54.LOCATION(CITY) 
	VALUES ('COLMAR');
INSERT INTO lo54.LOCATION(CITY) 
	VALUES ('NANCY');
INSERT INTO lo54.LOCATION(CITY) 
	VALUES ('METZ');


INSERT INTO lo54.COURSE_SESSION (START_DATE,END_DATE) 
	VALUES ('01/11/2017','03/11/2017');
INSERT INTO lo54.COURSE_SESSION (START_DATE,END_DATE) 
	VALUES ('05/01/2018','09/01/2018');
INSERT INTO lo54.COURSE_SESSION (START_DATE,END_DATE) 
	VALUES ('05/02/2018','09/02/2018');
INSERT INTO lo54.COURSE_SESSION (START_DATE,END_DATE) 
	VALUES ('05/03/2018','09/03/2018');


INSERT INTO lo54.COURSE (TITLE) 
	VALUES ('NET BEANS');
INSERT INTO lo54.COURSE (TITLE) 
	VALUES ('ECLIPSE');
INSERT INTO lo54.COURSE (TITLE) 
	VALUES ('MAVEN');
INSERT INTO lo54.COURSE (TITLE) 
	VALUES ('HIBERNATE');